## Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then interchange its rows and columns.

In [18]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns (transpose the array)
transposed_array = array_3x3.T

# Output the results
print("Original 3x3 Array:")
print(array_3x3)
print("\nTransposed Array (Interchanged Rows and Columns):")
print(transposed_array)

Original 3x3 Array:
[[84 50 85]
 [26  2 43]
 [54 12 34]]

Transposed Array (Interchanged Rows and Columns):
[[84 26 54]
 [50  2 12]
 [85 43 34]]


## Q2.  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [6]:
import numpy as np

# Generate a 1D array with 10 elements
array_1d = np.arange(10)  # or np.random.rand(10) for random values

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape it into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

# Output the arrays
print("1D Array:")
print(array_1d)
print("\n2x5 Array:")
print(array_2x5)
print("\n5x2 Array:")
print(array_5x2)

1D Array:
[0 1 2 3 4 5 6 7 8 9]

2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [7]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around it
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Output the arrays
print("4x4 Array with Random Floats:")
print(array_4x4)
print("\n6x6 Array with Border of Zeros:")
print(array_6x6)

4x4 Array with Random Floats:
[[0.01950998 0.69985779 0.37021267 0.29449858]
 [0.34296631 0.78186023 0.25438893 0.07035326]
 [0.43480346 0.99503756 0.68162156 0.33739233]
 [0.75724248 0.48922632 0.87994274 0.74433565]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.01950998 0.69985779 0.37021267 0.29449858 0.        ]
 [0.         0.34296631 0.78186023 0.25438893 0.07035326 0.        ]
 [0.         0.43480346 0.99503756 0.68162156 0.33739233 0.        ]
 [0.         0.75724248 0.48922632 0.87994274 0.74433565 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


## Q4.  Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [8]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array_integers = np.arange(10, 61, 5)

# Output the array
print(array_integers)

[10 15 20 25 30 35 40 45 50 55 60]


## Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
(uppercase, lowercase, title case, etc.) to each element.

In [9]:
import numpy as np

# Create a NumPy array of strings
array_strings = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(array_strings)
lowercase = np.char.lower(array_strings)
titlecase = np.char.title(array_strings)
capitalize = np.char.capitalize(array_strings)

# Output the transformed arrays
print("Original Array:")
print(array_strings)
print("\nUppercase:")
print(uppercase)
print("\nLowercase:")
print(lowercase)
print("\nTitle Case:")
print(titlecase)
print("\nCapitalize:")
print(capitalize)

Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalize:
['Python' 'Numpy' 'Pandas']


## Q6.  Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [10]:
import numpy as np

# Create a NumPy array of words
array_words = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', array_words)

# Output the transformed array
print("Original Array:")
print(array_words)
print("\nArray with Spaces Between Characters:")
print(spaced_words)

Original Array:
['hello' 'world' 'numpy' 'python']

Array with Spaces Between Characters:
['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


## Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [11]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10, 20, 30], [40, 50, 60]])

# Perform element-wise addition
addition = array1 + array2

# Perform element-wise subtraction
subtraction = array1 - array2

# Perform element-wise multiplication
multiplication = array1 * array2

# Perform element-wise division
division = array1 / array2

# Output the results
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nElement-wise Addition:")
print(addition)
print("\nElement-wise Subtraction:")
print(subtraction)
print("\nElement-wise Multiplication:")
print(multiplication)
print("\nElement-wise Division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[10 20 30]
 [40 50 60]]

Element-wise Addition:
[[11 22 33]
 [44 55 66]]

Element-wise Subtraction:
[[ -9 -18 -27]
 [-36 -45 -54]]

Element-wise Multiplication:
[[ 10  40  90]
 [160 250 360]]

Element-wise Division:
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


## Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [12]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Output the results
print("5x5 Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


## Q9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime number in this array.

In [13]:
import numpy as np

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Output the results
print("Random Integers Array:")
print(random_integers)
print("\nPrime Numbers in the Array:")
print(prime_numbers)

Random Integers Array:
[ 56  99 885  16 469 314 888 509 257 265 713 467 999 101 482 284 310 100
   1 392 282 186 404 151 849 545 623 721 895   5 871 391 602 738 876 622
 206  49 776 933 417 766 359 387 171 250 965 223 909 366 431 554   7  20
 837 315 401 566 104 752 470 328 801 106 388 478 154 254 317 586 392  36
 452 151 762 632 133 211 386  83 327 701 191 990  87 227 991 826 400 158
 593  72 274  99 791 331 622 263 910 739]

Prime Numbers in the Array:
[509, 257, 467, 101, 151, 5, 359, 223, 431, 7, 401, 317, 151, 211, 83, 701, 191, 227, 991, 593, 331, 263, 739]


## Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.s

In [17]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# For example, let's generate random temperatures between 0 and 100
daily_temperatures = np.random.randint(0, 101, size=30)

# Reshape the array to represent weeks (4 weeks and 2 extra days)
weekly_temperatures = daily_temperatures.reshape(10, 3)

# Calculate weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Output the results
print("Daily Temperatures for the Month:")
print(daily_temperatures)
print("\nWeekly Temperatures (4 weeks):")
print(weekly_temperatures)
print("\nWeekly Averages:")
print(weekly_averages)

Daily Temperatures for the Month:
[ 8 67 91  9 43 19 43 26 14 77 93  2 83 53 14 55 25 15 52  4 88 69 18 13
 98 51 61 30 68 87]

Weekly Temperatures (4 weeks):
[[ 8 67 91]
 [ 9 43 19]
 [43 26 14]
 [77 93  2]
 [83 53 14]
 [55 25 15]
 [52  4 88]
 [69 18 13]
 [98 51 61]
 [30 68 87]]

Weekly Averages:
[55.33333333 23.66666667 27.66666667 57.33333333 50.         31.66666667
 48.         33.33333333 70.         61.66666667]
